name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev
      - name: fmt
        run: make fmt
      - name: clippy
        run: make clippy
      - name: test
        run: make test
